# Generated by Django 5.0.2 on 2024-02-24 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('product', '0002_product_pdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(choices=[(2, 'Laptop'), (1, 'cell Phones'), (3, 'Cameras'), (14, 'electronics'), (11, 'home appliance')], default=1, on_delete=django.db.models.deletion.CASCADE, to='category.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='pimg',
            field=models.ImageField(blank=True, null=True, upload_to='product/images'),
        ),
    ]
